---
title: Comparing the size of penguin species
author: Colby Yurkiw
date: September 23, 2026
---

Data: [Palmer Penguins](https://allisonhorst.github.io/palmerpenguins/),
Palmer Station Antarctica LTER.


**Load Libraries**

_First we will load in pandas, matplotlib and palmerpenguins for our analysis of the penguins dataset._

```{python}
#| message: false
#| warning: false

import pandas as pd
import matplotlib.pyplot as plt
from palmerpenguins import load_penguins
```

**Looking at the data set**

_First, lets take a look at the dataset to see what we are working with._

```{python}
penguins = load_penguins()
print(penguins.head())

print([species for species, _ in penguins.groupby("species")])
```


_The data set includes 3 different species: Adelie, Chinstrap, and Gentoo penguins. There are entries for the penguins bills, flippers, origin, sex and measurement year._

**What are we analyzing**

_We will be analyzing the size differences between different species of penguins. The purpose of this analysis is to see if penguin species differ enough in size to visually distinguish the species simply based on physical measurements._

```{python}
penguins_grouped = penguins.groupby("species")
for species, group in penguins_grouped:
    print(f"{species:<15} {len(group)}")
```

_The most sampled species in the dataset is the Adelie species, followed by the Gentoo and the Chinstrap species._


**Visualization of Species Sizes**

_Now, we can do a visual comparison of the species by plotting._

```{python}
#| label: fig-penguin-species-sizes
#| fig-cap: Comparing bill length and body mass for penguin species


fig, axs = plt.subplots()

for species, group in penguins_grouped:
    axs.scatter(group["bill_length_mm"], group["body_mass_g"], label = species)

axs.set_xlabel("Bill Length (mm)")
axs.set_ylabel("Body Mass (g)")
axs.legend(title = "Species")

plt.show()
```


_We can observe a clear trend in the visual. Adelie penguins are on average, smaller on all metrics compared to Chinstrap and Gentoo. Gentoo penguins are larger than both Chinstrap and Adelie penguins in body mass, but have similar bill length to Chinstrap penguins. Therefore, it is possible to identify each of these species simply based on physical factors, however there is some overlap._
